version: '3.4'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  auth-service:
    build: ./auth-service
    ports:
      - "5005:5005"
    depends_on:
      db:
